### ISSUE TITLE
Battery status is not showing up

### ISSUE THREAD

**Issue by satya-vinay** [addy-dclxvi/i3-starterpack#5]
In i3 status bar the battery status is being empty.

**Comment by sambarnes** [comment]
I know this issue is mad old, but for me it was just a matter of switching from `"battery 1"` to `"battery 0"`

The integer makes the config look at a different filepath for the battery events https://github.com/addy-dclxvi/i3-starterpack/blob/master/.config/i3status/config#L64

So look in your `/sys/class/power_supply/` directory and see if `BAT0` is there

**Comment by jmrr** [comment]
Yeah same, also in https://github.com/jmrr/dotfiles/blob/2b2dcf1e86fb991610883d619c720fb5d253c1d1/i3config/i3status/config#L18-L19 you'll have to point to `battery 0`.
